baseURL = 'https://barral.email/'
disqusShortname = 'blog-do-barral'
languageCode = 'pt-BR'
title = 'Blog do Barral'
theme = 'PaperMod' 
description = "Documentando 140 Ã¡lbuns no iPod Video 5th Gen."

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
[[menu.main]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/@falabarral"
    weight = 20

[[menu.main]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/cwQp7BhsC5"
    weight = 30
	
[[menu.main]]
    identifier = "search"
    name = "Buscar"
    url = "/search/"
    weight = 5

[params]
    defaultTheme = "auto"
	ShowShareButtons = "true"
	ShowReadingTime = "true"
	ShowToc = "true"

[params.homeInfoParams]
        Title = "OlÃ¡! ðŸ‘‹"
        Content = "Bem-vindo ao Barral Log. Aqui documento o Protocolo 2026 e minha jornada."
	[[params.socialIcons]]
        name = "youtube"
        url = "https://youtube.com/@falabarral"
	[[params.socialIcons]]
        name = "discord"
        url = "https://discord.gg/cwQp7BhsC5"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/barral0"	

[outputs]
    home = ["HTML", "RSS", "JSON"]