baseURL = 'https://barral0.github.io/barral-log/'
languageCode = 'pt-BR'
title = 'Blog do Barral'
theme = 'PaperMod' 

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'