baseURL = 'https://barral.email/'
languageCode = 'pt-BR'
title = 'Blog do Barral'
theme = 'PaperMod' 
description = "Documentando 140 Ã¡lbuns no iPod Video 5th Gen."

[[menu.main]]
    identifier = "posts"
    name = "Reviews"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/@falabarral"
    weight = 20

[[menu.main]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/cwQp7BhsC5"
    weight = 30

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true