baseURL = 'https://barral.email/'
languageCode = 'pt-BR'
title = 'Blog do Barral'
theme = 'PaperMod' 

[params.profileMode]
    enabled = true
    title = "Filipe Barral"
    subtitle = "Ciência da Computação | QA Tester "
	imageUrl = "images/perfil.png"
    imageTitle = "Filipe Barral"
    
    [[params.profileMode.buttons]]
        name = "Reviews"
        url = "/posts"

	[[params.profileMode.buttons]]
        name = "YouTube"
        url = "https://youtube.com/@falabarral"
		
	[[params.profileMode.buttons]]
        name = "Discord"
        url = "https://discord.gg/cwQp7BhsC5"

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true
